name: silksong_alarm
description: "App of silksanity."
publish_to: "none"
version: 0.4.2

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  alarm: ^3.1.4
  # auto_start_flutter: ^0.1.1
  background_fetch: ^1.3.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  just_audio: ^0.9.38
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  volume_controller: ^2.0.7
  youtube_explode_dart: ^2.2.1

flutter_launcher_icons:
  image_path_android: "assets/app_icon.png"
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
